require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-hc
Style/Documentation:
  Enabled: false
AllCops:
  NewCops: enable
RSpec/MultipleExpectations:
  Max: 2
Layout/LineLength:
  Max: 200
Metrics/AbcSize:
  Max: 30
Metrics/MethodLength:
  Max: 35
Hc/RailsSpecificActionName:
  Exclude:
    - app/controllers/api/v1/users_controller.rb
